version: 2

models:
  - name: stg_library_checkouts
    description: "Staging table for Seattle Library Checkouts, focusing on years 2018-2020."
    columns:
      - name: title
        description: "Title of the item checked out."
      - name: isbn
        description: "ISBN of the item, if available."
      - name: publisher
        description: "Publisher of the item."
      - name: subjects
        description: "Subjects/categories related to the item."
      - name: material_type
        description: "The material format (e.g., BOOK, EBOOK, AUDIOBOOK)."
        tests:
          - not_null
      - name: checkout_year
        description: "Year when the checkout happened."
        tests:
          - not_null
      - name: checkout_month
        description: "Month when the checkout happened (1 to 12)."
      - name: checkouts
        description: "Number of times the item was checked out."
      - name: creator
        description: "Creator or author of the item."
      - name: usageclass
        description: "Usage classification (e.g., PHYSICAL, DIGITAL)."
      - name: checkouttype
        description: "Type of checkout transaction."
      - name: publication_year
        description: "Year of publication of the item."
